server:
  port: 8080
spring:
  application:
    name: incident-service
  data:
    mongodb:
      host: ${MONGODB_HOST:mongodb}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:context_support}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
services:
  sentiment:
    base-url: ${SENTIMENT_URL:http://sentiment-service:8082}
  notification:
    base-url: ${NOTIFICATION_URL:http://notification-service:8081}
