server:
  port: 8082
spring:
  application:
    name: sentiment-service
  data:
    mongodb:
      host: \${MONGODB_HOST:mongodb}
      port: \${MONGODB_PORT:27017}
      database: \${MONGODB_DATABASE:context_support}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
